#-------------------------------------------------------------------------------
# Note for using the rate-limiting:
#   The comment part won't be copied if you use the subgenerator docker-compose
#   you have to manually copy it
#-------------------------------------------------------------------------------
version: '2'
services:
    gatemicro-app:
        image: gatemicro
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://gatemicro-postgresql:5432/gatemicro
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=gatemicro-cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=gatemicro-elasticsearch:9300
        ports:
            - 8080:8080
    gatemicro-postgresql:
        extends:
            file: postgresql.yml
            service: gatemicro-postgresql
    # Uncomment to have Cassandra working with the gateway
    # gatemicro-cassandra:
    #     extends:
    #         file: cassandra-cluster.yml
    #         service: gatemicro-cassandra
    # gatemicro-cassandra-migration:
    #     extends:
    #         file: cassandra-migration.yml
    #         service: gatemicro-cassandra-migration
    #     environment:
    #         - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
    gatemicro-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: gatemicro-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
